const services=[
['Määräaikaishuolto','Huolto-ohjelman mukaista huolenpitoa.','⚙','Auton huolto valmistajan huolto-ohjelman mukaan. Työn laajuus määräytyy auton mallin, iän ja ajomäärän perusteella.','Kun auton huoltoväli täyttyy tai huoltomuistutin ilmoittaa huollon tarpeesta.'],
['Vikadiagnostiikka','Selvitetään, mistä vika johtuu.','⌁','Vikakoodien luku ja vianhaku auttavat selvittämään häiriön syyn ja tarvittavat jatkotoimet.','Kun varoitusvalo syttyy, käynti muuttuu epätasaiseksi tai autossa ilmenee poikkeava toimintahäiriö.'],
['Jarruhuolto','Varmuutta jokaiseen pysähdykseen.','◎','Jarrujen kunnon tarkastus ja tarvittavat korjaukset. Kysy tarjous esimerkiksi jarrupalojen ja -levyjen vaihtoon.','Kun jarrut pitävät ääntä, täristävät tai jarrutustuntuma on muuttunut.'],
['Ilmastointihuolto','Mukavuutta kaikkiin vuodenaikoihin.','❄','Ilmastointijärjestelmän huolto ja toimintahäiriöiden selvitys. Työn sisältö sovitaan autosi järjestelmän mukaan.','Kun ilmastointi ei viilennä tavalliseen tapaan tai järjestelmän huolto on ajankohtainen.'],
['Jakohihnan vaihto','Ennakoi. Pidä moottorista huolta.','◷','Jakohihnan vaihtotyö autosi moottorin ja valmistajan ohjeiden mukaan. Kerro auton rekisteritunnus tarjousta varten.','Kun valmistajan määrittämä aika- tai kilometriraja lähestyy.'],
['Rengaspalvelut','Pitoa vaihtuviin olosuhteisiin.','⊙','Renkaisiin ja vanteisiin liittyvät työt. Kuvaile tarvitsetko kausivaihdon vai muuta rengastyötä.','Kun kausi vaihtuu, renkaat kuluvat tai tarvitset apua renkaiden kanssa.'],
['Katsastuskorjaukset','Viat kuntoon, matka jatkuu.','✓','Katsastuksessa havaittujen vikojen korjaukset. Katsastuksen vikalista auttaa arvioimaan työn laajuuden.','Kun autosi tarvitsee korjausta katsastuksen jälkeen tai ennen seuraavaa katsastusta.'],
['Öljynvaihto','Moottorin hyvinvoinnin perusta.','◇','Moottoriöljyn ja öljynsuodattimen vaihtotyö autosi vaatimusten mukaan.','Kun öljynvaihtoväli täyttyy ajan tai ajokilometrien perusteella.']];
const grid=document.querySelector('#services'),select=document.querySelector('#service-select'),dialog=document.querySelector('#service-dialog');
services.forEach(([title,short,icon,description,symptoms],i)=>{const button=document.createElement('button');button.className='service';button.innerHTML=`<span class="service-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><span class="arrow" aria-hidden="true">↗</span><strong>${title}</strong><small>${short}</small><span class="service-more">Tutustu palveluun <span aria-hidden="true">→</span></span>`;button.setAttribute('aria-haspopup','dialog');button.onclick=()=>{document.querySelector('#dialog-title').textContent=title;document.querySelector('#dialog-description').textContent=description;document.querySelector('#dialog-symptoms').textContent=symptoms;dialog.showModal()};grid.append(button);const option=document.createElement('option');option.value=title;option.textContent=title;select.append(option)});
document.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Sulje valikko':'Avaa valikko')};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Avaa valikko')});document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
const form=document.querySelector('#booking-form'),statusBox=document.querySelector('#form-status'),submit=form.querySelector('[type=submit]');
let requestId=crypto.randomUUID();
const dateField=form.elements.date;
function validateDate(){const result=SuniDate.parse(dateField.value);dateField.setCustomValidity(result===null?'Anna päivä muodossa PP.KK.VVVV.':result&&result<SuniDate.today()?'Valitse tämä päivä tai tuleva päivä.':'');return result}
dateField.addEventListener('input',validateDate);dateField.addEventListener('blur',()=>{const value=validateDate();if(value)dateField.value=SuniDate.format(value)});
const calendar=document.querySelector('#date-picker'),calendarDays=document.querySelector('#calendar-days');let calendarMonth;
function renderCalendar(){const year=calendarMonth.getUTCFullYear(),month=calendarMonth.getUTCMonth(),today=SuniDate.today(),selected=SuniDate.parse(dateField.value);document.querySelector('#calendar-title').textContent=new Intl.DateTimeFormat('fi-FI',{month:'long',year:'numeric',timeZone:'UTC'}).format(calendarMonth);calendarDays.replaceChildren();const offset=(new Date(Date.UTC(year,month,1)).getUTCDay()+6)%7;for(let n=0;n<offset;n++){const blank=document.createElement('span');calendarDays.append(blank)}const count=new Date(Date.UTC(year,month+1,0)).getUTCDate();for(let day=1;day<=count;day++){const iso=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;const button=document.createElement('button');button.type='button';button.textContent=day;button.disabled=iso<today;button.setAttribute('aria-label',SuniDate.format(iso));button.setAttribute('aria-pressed',String(iso===selected));button.onclick=()=>{dateField.value=SuniDate.format(iso);validateDate();calendar.close();dateField.focus()};calendarDays.append(button)}document.querySelector('#previous-month').disabled=`${year}-${String(month+1).padStart(2,'0')}`<=today.slice(0,7)}
document.querySelector('#open-calendar').onclick=()=>{const selected=SuniDate.parse(dateField.value),base=selected&&selected>=SuniDate.today()?selected:SuniDate.today();calendarMonth=new Date(base.slice(0,7)+'-01T00:00:00Z');renderCalendar();calendar.showModal()};calendar.querySelector('.close').onclick=()=>calendar.close();document.querySelector('#previous-month').onclick=()=>{calendarMonth.setUTCMonth(calendarMonth.getUTCMonth()-1);renderCalendar()};document.querySelector('#next-month').onclick=()=>{calendarMonth.setUTCMonth(calendarMonth.getUTCMonth()+1);renderCalendar()};document.querySelector('#clear-date').onclick=()=>{dateField.value='';validateDate();calendar.close();dateField.focus()};
dialog.querySelector('a').addEventListener('click',()=>{select.value=document.querySelector('#dialog-title').textContent;dialog.close()});
document.querySelectorAll('a[href="#ajanvaraus"]').forEach(a=>a.addEventListener('click',()=>{if(a.textContent.toLowerCase().includes('tarjous'))form.elements.type.value='quote'}));
const privacy=document.querySelector('#privacy-dialog');document.querySelectorAll('.privacy-link').forEach(b=>b.onclick=()=>privacy.showModal());privacy.querySelector('.close').onclick=()=>privacy.close();
form.addEventListener('submit',async event=>{event.preventDefault();validateDate();if(!form.reportValidity())return;submit.disabled=true;submit.textContent='Lähetetään…';statusBox.className='';statusBox.textContent='';const body=Object.fromEntries(new FormData(form));body.date=SuniDate.parse(body.date);body.id=requestId;body.consent=Boolean(body.consent);try{const response=await fetch('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let result;try{result=await response.json()}catch{throw Error('Palvelu ei vastaa. Yritä hetken kuluttua uudelleen.')}if(!response.ok)throw Error(result.error||'Pyyntöä ei voitu tallentaa. Yritä uudelleen.');statusBox.className='success';statusBox.textContent=`Kiitos! Pyyntösi on tallennettu. Tunniste: ${result.reference}. Huoltoaika vahvistetaan erikseen.`;form.reset();requestId=crypto.randomUUID()}catch(error){statusBox.className='error';statusBox.textContent=error.message}finally{submit.disabled=false;submit.innerHTML='Lähetä pyyntö <span>↗</span>'}});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'prepare_service_request',description:'Valitse palvelu ja avaa huoltopyyntölomake. Ei lähetä pyyntöä.',inputSchema:{type:'object',properties:{service:{type:'string',enum:services.map(s=>s[0])}},required:['service'],additionalProperties:false},execute(input){if(!input||!services.some(s=>s[0]===input.service))throw Error('Tuntematon palvelu');select.value=input.service;form.scrollIntoView({behavior:'smooth'});return {service:select.value,submitted:false}}})).catch(()=>{})}catch{}}

const quickService=document.querySelector('#quick-service');services.forEach(([title])=>{const option=document.createElement('option');option.value=title;option.textContent=title;quickService.append(option)});document.querySelector('#start-booking').onclick=()=>{select.value=quickService.value||'Muu korjaus';form.scrollIntoView({behavior:'smooth',block:'start'});form.elements.registration.focus({preventScroll:true})};
